version: '2'
services:
  node:
    image: node:10.16.0-alpine
    volumes:
      - .:/usr/src/app:z
    working_dir: /usr/src/app

  yarn:
    extends:
      service: node
    entrypoint: yarn

  dev:
    extends:
      service: yarn
    command: dev
    ports:
      - "8080:80"
    environment:
      - PORT=80
      - NODE_ENV=development
